import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center flex-col gap-6 bg-white text-black dark:bg-black dark:text-white h-screen text-2xl">
        <h1 className="text-6xl font-sans font-bold">
          Welcome to{' '}
          <a
            href="https://nextjs.org"
            className="text-blue-500 hover:underline duration-200"
          >
            Next.js!
          </a>
        </h1>

        <p>
          Get started by editing{' '}
          <code className=" bg-[#111] p-2 rounded-lg font-mono italic select-all">
            pages/index.js
          </code>
        </p>
      </main>
    </div>
  );
}
