import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center flex-col gap-6 bg-background text-white h-screen text-2xl">
        <h1 className="text-6xl font-sans font-bold">
          Welcome to{" "}
          <a
            href="https://nextjs.org"
            className="text-blue-500 hover:underline duration-200"
          >
            WEA
          </a>
        </h1>
        <p>Web entrepreneur assistance </p>
      </main>
    </div>
  );
}
